# 6 Pandas的函数应用

In [1]:
import pandas as pd
import numpy as np
# Numpy ufunc 函数，randn跟的是维数
df = pd.DataFrame(np.random.randn(5,4) - 1)
print(df)

print(np.abs(df)) #绝对值

          0         1         2         3
0 -3.444370 -2.356444 -0.918663 -1.592337
1 -1.248756 -1.968575 -0.534197 -0.546866
2 -3.476581 -0.671513 -0.293116 -1.725876
3 -1.182100 -1.328248 -0.923086 -0.579832
4 -2.237880 -0.579494 -1.545391 -0.420245
          0         1         2         3
0  3.444370  2.356444  0.918663  1.592337
1  1.248756  1.968575  0.534197  0.546866
2  3.476581  0.671513  0.293116  1.725876
3  1.182100  1.328248  0.923086  0.579832
4  2.237880  0.579494  1.545391  0.420245


In [2]:
#apply默认作用在列上,x是每一列,因为axis=0
print(df.apply(lambda x : x.max()))

0   -1.182100
1   -0.579494
2   -0.293116
3   -0.420245
dtype: float64


In [3]:
#apply作用在行上
print(df.apply(lambda x : x.max(), axis=1))

0   -0.918663
1   -0.534197
2   -0.293116
3   -0.579832
4   -0.420245
dtype: float64


In [5]:
# 使用applymap应用到每个数据
print(df.map(lambda x : '%.2f' % x))
df.dtypes

       0      1      2      3
0  -3.44  -2.36  -0.92  -1.59
1  -1.25  -1.97  -0.53  -0.55
2  -3.48  -0.67  -0.29  -1.73
3  -1.18  -1.33  -0.92  -0.58
4  -2.24  -0.58  -1.55  -0.42


0    float64
1    float64
2    float64
3    float64
dtype: object

In [6]:
type('%.2f' % 1.3456)

str

## 6.4 索引排序

In [7]:
# Series
print(np.random.randint(5, size=5))
s4 = pd.Series(range(10, 15), index = np.random.randint(5, size=5)) #索引随机生成
print(s4)
print('-'*50)
# 索引排序,sort_index返回一个新的排好索引的series
print(s4.sort_index())
print(s4)
# s4.loc[0:3]  loc索引值不唯一时直接报错
print(s4.iloc[0:3])
s4[0:3]  #默认用的位置索引

[2 2 3 4 3]
2    10
4    11
4    12
1    13
2    14
dtype: int64
--------------------------------------------------
1    13
2    10
2    14
4    11
4    12
dtype: int64
2    10
4    11
4    12
1    13
2    14
dtype: int64
2    10
4    11
4    12
dtype: int64


2    10
4    11
4    12
dtype: int64

In [8]:
# s4.loc[1:2] #loc索引值唯一时可以切片

In [8]:
# DataFrame
df4 = pd.DataFrame(np.random.randn(5, 5),
                   index=np.random.randint(5, size=5),
                   columns=np.random.randint(5, size=5))
print(df4)
#轴零是行索引排序
df4_isort = df4.sort_index(axis=0, ascending=False)
print(df4_isort)


          1         4         3         0         1
1 -0.311745  1.140897  1.323763  1.805976 -2.173504
2 -1.413020  0.103831 -0.039302  0.933795  0.769106
3  0.731249  1.491838 -0.481012 -0.201339  0.708635
0  1.380481 -0.189336  0.901411  0.241788  0.785989
4  1.753742  0.962466  0.660472  0.225853 -0.506865
          1         4         3         0         1
4  1.753742  0.962466  0.660472  0.225853 -0.506865
3  0.731249  1.491838 -0.481012 -0.201339  0.708635
2 -1.413020  0.103831 -0.039302  0.933795  0.769106
1 -0.311745  1.140897  1.323763  1.805976 -2.173504
0  1.380481 -0.189336  0.901411  0.241788  0.785989


In [9]:
#轴1是列索引排序
df4_isort = df4.sort_index(axis=1, ascending=True)
print(df4_isort)

          0         1         1         3         4
1  1.805976 -0.311745 -2.173504  1.323763  1.140897
2  0.933795 -1.413020  0.769106 -0.039302  0.103831
3 -0.201339  0.731249  0.708635 -0.481012  1.491838
0  0.241788  1.380481  0.785989  0.901411 -0.189336
4  0.225853  1.753742 -0.506865  0.660472  0.962466


# 6.5 按值排序（机器学习，深度学习不重要，数据分析才需要）

In [12]:
# 按值排序,by后是column的值
import random
l=[random.randint(0,100) for i in range(24)] #生成24个随机数
df4 = pd.DataFrame(np.array(l).reshape(6,4)) #生成6行4列的dataframe
print(df4.values) #查看数据,ndarray
print('-'*50)
print(df4)
print('-'*50)
#按轴零排序，by后是列名,交换的是行
df4_vsort = df4.sort_values(by=3,axis=0, ascending=False) #寻找的是columns里的3,重要
print(df4_vsort)


[[11 57 96 82]
 [93 78 65 76]
 [59 25 33 43]
 [ 9 16 42 75]
 [42 73 36 75]
 [96 12 85 77]]
--------------------------------------------------
    0   1   2   3
0  11  57  96  82
1  93  78  65  76
2  59  25  33  43
3   9  16  42  75
4  42  73  36  75
5  96  12  85  77
--------------------------------------------------
    0   1   2   3
0  11  57  96  82
5  96  12  85  77
1  93  78  65  76
3   9  16  42  75
4  42  73  36  75
2  59  25  33  43


In [13]:
#按轴1排序，by后行索引名，交换的是列
df4_vsort = df4.sort_values(by=3,axis=1, ascending=False) #寻找的是index里的3
print(df4_vsort)

    3   2   1   0
0  82  96  57  11
1  76  65  78  93
2  43  33  25  59
3  75  42  16   9
4  75  36  73  42
5  77  85  12  96


# 6.6 处理缺失数据

In [14]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0         1         2
0 -0.001544  1.640912  0.592077
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000


In [15]:
df_data.iloc[2,0]

np.float64(nan)

In [16]:
#isnull来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


## 删除缺失数据

In [20]:
#默认一个样本，任何一个特征缺失，就删除
#inplace True是修改的是原有的df
#subset=[0]是指按第一列来删除,第一列有空值就删除对应的行
print(df_data.dropna(subset=[0]))
# df_data

          0         1         2
0 -0.001544  1.640912  0.592077
1  1.000000  2.000000       NaN
3  1.000000  2.000000  3.000000


In [21]:
df_data

0         1         2
0 -0.001544  1.640912  0.592077
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [22]:
#用的不多，某个特征缺失太多时
print(df_data.dropna(axis=1))  #某列由nan就删除该列

          1
0  1.640912
1  2.000000
2  4.000000
3  2.000000


In [23]:
df_data

0         1         2
0 -0.001544  1.640912  0.592077
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

## 填充缺失数据

In [26]:
#给零列的空值填为-100，按特征（按列）去填充
print(df_data.iloc[:,0].fillna(-100.))
df_data

0     -0.001544
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64


0         1         2
0 -0.001544  1.640912  0.592077
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000

In [27]:
#依次拿到每一列
for i in df_data.columns:
    print(df_data.loc[:,i])

0   -0.001544
1    1.000000
2         NaN
3    1.000000
Name: 0, dtype: float64
0    1.640912
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64
0    0.592077
1         NaN
2         NaN
3    3.000000
Name: 2, dtype: float64
