# 6 Pandas的函数应用

In [1]:
import pandas as pd
import numpy as np
# Numpy ufunc 函数，randn跟的是维数
df = pd.DataFrame(np.random.randn(5,4) - 1)
print(df)

print(np.abs(df)) #绝对值

          0         1         2         3
0 -1.796757 -2.923411 -2.736810 -0.859848
1 -0.224980 -1.621999  0.146745 -0.358529
2 -0.168885 -1.145974  0.900158 -2.156192
3 -0.970115 -0.769003 -0.845359 -0.819728
4 -1.781478  0.049375  0.195091 -0.586308
          0         1         2         3
0  1.796757  2.923411  2.736810  0.859848
1  0.224980  1.621999  0.146745  0.358529
2  0.168885  1.145974  0.900158  2.156192
3  0.970115  0.769003  0.845359  0.819728
4  1.781478  0.049375  0.195091  0.586308


In [2]:
#apply默认作用在列上,x是每一列,因为axis=0
print(df.apply(lambda x : x.max()))

0   -0.168885
1    0.049375
2    0.900158
3   -0.358529
dtype: float64


In [3]:
#apply作用在行上
print(df.apply(lambda x : x.max(), axis=1))

0   -0.859848
1    0.146745
2    0.900158
3   -0.769003
4    0.195091
dtype: float64


In [4]:
# 使用applymap应用到每个数据
print(df.applymap(lambda x : '%.2f' % x))
df.dtypes

       0      1      2      3
0  -1.80  -2.92  -2.74  -0.86
1  -0.22  -1.62   0.15  -0.36
2  -0.17  -1.15   0.90  -2.16
3  -0.97  -0.77  -0.85  -0.82
4  -1.78   0.05   0.20  -0.59


0    float64
1    float64
2    float64
3    float64
dtype: object

In [5]:
type('%.2f' % 1.3456)

str

## 6.4 索引排序

In [6]:
# Series
print(np.random.randint(5, size=5))
s4 = pd.Series(range(10, 15), index = np.random.randint(5, size=5)) #索引随机生成
print(s4)
print('-'*50)
# 索引排序,sort_index返回一个新的排好索引的series
print(s4.sort_index())
print(s4)
# s4.loc[0:3]  loc索引值不唯一时直接报错
print(s4.iloc[0:3])
s4[0:3]  #默认用的位置索引

[2 4 3 1 1]
2    10
0    11
1    12
0    13
0    14
dtype: int64
--------------------------------------------------
0    11
0    13
0    14
1    12
2    10
dtype: int64
2    10
0    11
1    12
0    13
0    14
dtype: int64
2    10
0    11
1    12
dtype: int64


2    10
0    11
1    12
dtype: int64

In [8]:
# s4.loc[1:2] #loc索引值唯一时可以切片

In [7]:
# DataFrame
df4 = pd.DataFrame(np.random.randn(5, 5),
                   index=np.random.randint(5, size=5),
                   columns=np.random.randint(5, size=5))
print(df4)
#轴零是行索引排序
df4_isort = df4.sort_index(axis=0, ascending=False)
print(df4_isort)


          0         3         2         3         0
0 -0.137610 -0.858287 -0.486837 -0.018233  1.223872
1  0.026397 -0.063860  0.085134  0.232169  0.426953
2 -1.281888 -0.910263  1.482847 -0.947013  0.401932
3  0.603027  1.002181  1.451099  0.564141  0.076904
1  0.001383 -1.250364 -1.222472 -1.596742  0.732299
          0         3         2         3         0
3  0.603027  1.002181  1.451099  0.564141  0.076904
2 -1.281888 -0.910263  1.482847 -0.947013  0.401932
1  0.026397 -0.063860  0.085134  0.232169  0.426953
1  0.001383 -1.250364 -1.222472 -1.596742  0.732299
0 -0.137610 -0.858287 -0.486837 -0.018233  1.223872


In [9]:
#轴1是列索引排序
df4_isort = df4.sort_index(axis=1, ascending=True)
print(df4_isort)

          0         0         2         3         3
0 -0.137610  1.223872 -0.486837 -0.858287 -0.018233
1  0.026397  0.426953  0.085134 -0.063860  0.232169
2 -1.281888  0.401932  1.482847 -0.910263 -0.947013
3  0.603027  0.076904  1.451099  1.002181  0.564141
1  0.001383  0.732299 -1.222472 -1.250364 -1.596742


# 6.5 按值排序（机器学习，深度学习不重要，数据分析才需要）

In [10]:
# 按值排序,by后是column的值
import random
l=[random.randint(0,100) for i in range(24)] #生成24个随机数
df4 = pd.DataFrame(np.array(l).reshape(6,4)) #生成6行4列的dataframe
print(df4.values) #查看数据,ndarray
print('-'*50)
print(df4)
print('-'*50)
#按轴零排序，by后是列名,交换的是行
df4_vsort = df4.sort_values(by=3,axis=0, ascending=False) #寻找的是columns里的3,重要
print(df4_vsort)


[[ 65  21  58  61]
 [ 88  25  35  86]
 [ 65  28  63   5]
 [ 64  45  95  23]
 [  0  92  57 100]
 [ 52  57  89  24]]
--------------------------------------------------
    0   1   2    3
0  65  21  58   61
1  88  25  35   86
2  65  28  63    5
3  64  45  95   23
4   0  92  57  100
5  52  57  89   24
--------------------------------------------------
    0   1   2    3
4   0  92  57  100
1  88  25  35   86
0  65  21  58   61
5  52  57  89   24
3  64  45  95   23
2  65  28  63    5


In [11]:
#按轴1排序，by后行索引名，交换的是列
df4_vsort = df4.sort_values(by=3,axis=1, ascending=False) #寻找的是index里的3
print(df4_vsort)

    2   0   1    3
0  58  65  21   61
1  35  88  25   86
2  63  65  28    5
3  95  64  45   23
4  57   0  92  100
5  89  52  57   24


# 6.6 处理缺失数据

In [12]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

         0         1         2
0  0.77195  0.039062 -0.585232
1  1.00000  2.000000       NaN
2      NaN  4.000000       NaN
3  1.00000  2.000000  3.000000


In [13]:
df_data.iloc[2,0]

nan

In [14]:
#isnull来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


## 删除缺失数据

In [17]:
#默认一个样本，任何一个特征缺失，就删除
#inplace True是修改的是原有的df
#subset=[0]是指按第一列来删除,第一列有空值就删除对应的行
print(df_data.dropna(subset=[0]))
# df_data

         0         1         2
0  0.77195  0.039062 -0.585232
3  1.00000  2.000000  3.000000


In [16]:
df_data

0         1         2
0  0.77195  0.039062 -0.585232
1  1.00000  2.000000       NaN
2      NaN  4.000000       NaN
3  1.00000  2.000000  3.000000

In [18]:
#用的不多，某个特征缺失太多时
print(df_data.dropna(axis=1))  #某列由nan就删除该列

          1
0  0.039062
1  2.000000
2  4.000000
3  2.000000


In [19]:
df_data

0         1         2
0  0.77195  0.039062 -0.585232
1  1.00000  2.000000       NaN
2      NaN  4.000000       NaN
3  1.00000  2.000000  3.000000

## 填充缺失数据

In [21]:
#给零列的空值填为-100，按特征（按列）去填充
print(df_data.iloc[:,0].fillna(-100.))
df_data

0      0.77195
1      1.00000
2   -100.00000
3      1.00000
Name: 0, dtype: float64


0         1         2
0  0.77195  0.039062 -0.585232
1  1.00000  2.000000       NaN
2      NaN  4.000000       NaN
3  1.00000  2.000000  3.000000

In [22]:
#依次拿到每一列
for i in df_data.columns:
    print(df_data.loc[:,i])

0    0.77195
1    1.00000
2        NaN
3    1.00000
Name: 0, dtype: float64
0    0.039062
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64
0   -0.585232
1         NaN
2         NaN
3    3.000000
Name: 2, dtype: float64
