In [26]:
import random
import numpy as np
import time

In [27]:
a = []
for i in range(1000000):
    a.append(random.random())
start_time = time.time()
sum1 = sum(a)
end_time = time.time()
print("Sum of 1 million random numbers using sum() function: ", sum1)
print("Time taken to calculate sum: ", end_time - start_time, "seconds")

Sum of 1 million random numbers using sum() function:  499900.38121432037
Time taken to calculate sum:  0.0050029754638671875 seconds


In [28]:
b = np.array(a)
start_time = time.time()
sum2 = np.sum(b)
end_time = time.time()
print("Sum of 1 million random numbers using numpy.sum() function: ", sum2)
print("Time taken to calculate sum: ", end_time - start_time, "seconds")

Sum of 1 million random numbers using numpy.sum() function:  499900.3812143072
Time taken to calculate sum:  0.0019905567169189453 seconds


# 4.1创建一维数组

In [29]:
list1 = [1,2,3,4]
#列表强制转换为数组
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [30]:
#1、直接通过传入列表创造数组
t1 = np.array([1,2,3,4])
print(t1)
print(type(t1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [31]:
#2、传入range生产序列
t2 = np.array(range(12))
print(t2)
print(type(t2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [32]:
#3、使用numpy自带的np.arange()函数生成序列
t3 = np.arange(0,12,2)
print(t3)
print(type(t3))

[ 0  2  4  6  8 10]
<class 'numpy.ndarray'>


# 4.2创建二维数组

In [33]:
#1、直接通过传入列表创造二维数组
list2 = [[1,2,3],[4,5,6],[7,8,9]]
twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 4.3常用属性

In [34]:
#1、获取数组的维数
print(oneArray.ndim)
print(twoArray.ndim)

1
2


In [35]:
#2、获取数组的元素个数
print(oneArray.size)
print(twoArray.size)

4
9


In [36]:
#3、获取数组的形状
print(oneArray.shape)
print(twoArray.shape)

(4,)
(3, 3)


# 4.4调整数组的形状

In [37]:
#通过reshape()方法调整数组的形状
four = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(four)
print(four.shape)
four.shape = (3,4)
print(four)
print(four.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [38]:
#重新调整数组的形状，返回新数组
four = four.reshape(4,3)
print(four)
print(four.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [42]:
#将多维数组变成一维数组,
#C是按行优先，F是按列优先
five = four.reshape((12,),order='C')
six = four.reshape((12,),order='F')
print(six)
print(five)
print(four)

[ 1  4  7 10  2  5  8 11  3  6  9 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
t = np.arange(24)
print(t)
print(t.shape)
t1 = t.reshape((2,3,4))
print(t1)
print(t1.shape)
print('-'*50)
t2 = t1.reshape((4,3,2))
print(t2.shape)
t3 = t2.reshape((2,12))
print(t3.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
--------------------------------------------------
(4, 3, 2)
(2, 12)


# 4.5将数组转换成list

In [52]:
#将数组转换成列表,区别在于有没有,
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
b = a.tolist()
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# 5 numpy的数据类型

In [54]:
import random
#返回数组中每个元素的字节单位长度，dtype设置数据类型
f =np.array([1,2,3,4,5],dtype=np.int16)

#itemsize获取数组中每个元素的字节单位长度
print(f.itemsize)

#获取数组的类型
print(f.dtype)

2
int16


In [55]:
#调整数据类型
f1 = f.astype(np.float32)
print(f1.dtype)

float32


In [61]:
#随机生成小数，并保留两位小数
print(round(random.random(),2))

0.48


In [62]:
arr = np.array([random.random() for i in range(10)])
print(arr)
print(np.round(arr,2))

[0.13520959 0.44684056 0.94402364 0.71784025 0.04954232 0.42563946
 0.15479646 0.62817422 0.23527841 0.74660904]
[0.14 0.45 0.94 0.72 0.05 0.43 0.15 0.63 0.24 0.75]


# 6 numpy的运算
# 6.1数组和数的运算

In [64]:
t1 = np.arange(24).reshape(6,4)
print(t1)
print('-'*50)
print(t1+2)
print('-'*50)
print(t1*2)
print('-'*50)
print(t1/2)
print('-'*50)
print(t1**2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------------------------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------------------------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------------------------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]
--------------------------------------------------
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]]


# 6.2数组和数组的运算

In [73]:
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))

print(t1+t2)
print('-'*50)
print(t1*t2)
print('-'*50)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]
--------------------------------------------------


In [80]:
#行形状相同，列形状不同
#(6,4)-(6,1),每一列减去相同的数
t3 = np.arange(0,6).reshape((6,1))
print(t3.shape)

print(t1-t3)
print((t1-t3).shape)

(6, 1)
[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]
 [12 13 14 15]
 [15 16 17 18]]
(6, 4)


In [81]:
#列形状相同，行形状不同
#(6,4)-(1,4),每一行减去相同的数
t4 = np.arange(0,4).reshape((1,4))
print(t4.shape)

print(t1-t4)
print((t1-t4).shape)

(1, 4)
[[ 0  0  0  0]
 [ 4  4  4  4]
 [ 8  8  8  8]
 [12 12 12 12]
 [16 16 16 16]
 [20 20 20 20]]
(6, 4)


# 结论谁相同，谁就变

# 6.3数组的轴

In [83]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('-'*50)
#按行进行运算
print(a.sum(axis=0))
print('-'*50)
#按列进行运算
print(a.sum(axis=1))
print('-'*50)
print(a.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[12 15 18]
--------------------------------------------------
[ 6 15 24]
--------------------------------------------------
45


In [87]:
a = np.arange(27).reshape(3,3,3)
print(a)
print('-'*50)
#按0轴进行运算
print(a.sum(axis=0))
print('-'*50)
#按1轴进行运算
print(a.sum(axis=1))
print('-'*50)
#按3轴进行运算
print(a.sum(axis=2))
print('-'*50)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------------------------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------------------------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------------------------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
--------------------------------------------------


# 7数组的切片

# 7.1一维数组的切片

In [90]:
a = np.arange(10)
#a[2]是取第3个元素，a[2:]是取从第3个元素到最后的元素
print(a[2],a)
print(a[2:])

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


# 7.2多维数组的切片

In [97]:
t1 = np.arange(16).reshape(4,4)
print(t1)
print('-'*50)

#取第二行
print(t1[1])
print('-'*50)

#取第二列
print(t1[:,1])
print('-'*50)

#取第2行的第3列
print(t1[1][2])
print('-'*50)

#取第2行到第4行
print(t1[1:3])
print('-'*50)

#取第2行到第3行的第2列到第3列
print(t1[1:3,1:3])
print('-'*50)

#取第2行到第4行的第2列到第4列
print(t1[1:3,1:4])
print('-'*50)

#取不连续的多行
#取第0、2、3行
print(t1[[0,2]])
print('-'*50)

#取不连续的多列
#取第0、2、3列
print(t1[:,[0,2]])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------------------------------------------
[4 5 6 7]
--------------------------------------------------
[ 1  5  9 13]
--------------------------------------------------
6
--------------------------------------------------
[[ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
[[ 5  6]
 [ 9 10]]
--------------------------------------------------
[[ 5  6  7]
 [ 9 10 11]]
--------------------------------------------------
[[ 0  1  2  3]
 [ 8  9 10 11]]
--------------------------------------------------
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


# 8.1 数组中的数值修改

In [101]:
t = np.arange(24).reshape(4,6)
print(t)
print('-'*50)

#修改某一行的值
#t[1,:]表示t的第2行，:表示取所有列
t[1,:]=0
print(t)
print('-'*50)

#修改某一列的值
#t[:,2]表示t的所有行的第3列
t[:,2]=0
print(t)
print('-'*50)

#修改某一个元素的值
t[1,2]=100
print(t)
print('-'*50)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  1  0  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13  0 15 16 17]
 [18 19  0 21 22 23]]
--------------------------------------------------
[[  0   1   0   3   4   5]
 [  0   0 100   0   0   0]
 [ 12  13   0  15  16  17]
 [ 18  19   0  21  22  23]]
--------------------------------------------------


In [107]:
t1 = np.arange(24).reshape(4,6)
print(t1)
print('-'*50)

#修改多行多列的值,同时满足条件
t1[1:3,2:4] = 0
print(t1)
print('-'*50)

#修改多个点的值
t1[[0,2],[1,5]] = 0
print(t1)
print('-'*50)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  0  0 10 11]
 [12 13  0  0 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  0  2  3  4  5]
 [ 6  7  0  0 10 11]
 [12 13  0  0 16  0]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  0  2  3  4  5]
 [ 6  7  0  0 10  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


# 8.2根据逻辑条件修改数组的值

In [110]:
t = np.arange(24).reshape(4,6)
print(t)
print('-'*50)

#将大于10的元素修改为10
t[t>10] = 10
print(t)
print('-'*50)

#将小于2或者大于9的元素修改为0
#多个表达式之间用&表示与运算，别忘了要有括号
t[(t<2) & (t>9)] = 0
print(t)
print('-'*50)

#三目运算where
score = np.array([[80,88],[82,81],[75,81]])
result = np.where(score>=80, '及格', '不及格')
print(result)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
--------------------------------------------------
[['及格' '及格']
 ['及格' '及格']
 ['不及格' '及格']]


# 9数组的添加、删除、去重

# 9.1数组的添加

In [116]:
a = np.array([[1,2,3],[4,5,6]])
print('第一个数组：')
print(a)

#数组的添加
#append()方法可以将数组添加到原数组的尾部,并且展开成一维数组
print('数组的添加：')
print(np.append(a, [[7,8,9]]))

print('沿轴0数组的添加：')
print(np.append(a, [[7,8,9]],axis=0))

print('沿轴1数组的添加：')
print(np.append(a, [[7,8,9],[5,5,5]],axis=1))



第一个数组：
[[1 2 3]
 [4 5 6]]
数组的添加：
[1 2 3 4 5 6 7 8 9]
沿轴0数组的添加：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
沿轴1数组的添加：
[[1 2 3 7 8 9]
 [4 5 6 5 5 5]]


# 9.2数组的删除

In [119]:
a = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)

print('未传递Axis参数。在删除之前数组会被展开')
print(np.delete(a, 5))

print('删除每一行的第二列')
print(np.delete(a, 1, axis=1))


第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
未传递Axis参数。在删除之前数组会被展开
[ 0  1  2  3  4  6  7  8  9 10 11]
删除每一行的第二列
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


# 9.3数组的去重

In [123]:
a = np.array([1,2,3,2,1,4,5,4,3,2,1])
print('第一个数组：')
print(a)

print('数组的去重：')
print(np.unique(a))

print('去重数组的索引数组')
u, indices = np.unique(a, return_index=True)

#indices是原始数组中每个元素的索引
print(indices)

#u是去重后的数组
print(u)

print('返回去重元素的个数')
u, counts = np.unique(a, return_counts=True)

#counts是每个元素的个数
print(counts)

#u是去重后的数组
print(u)

第一个数组：
[1 2 3 2 1 4 5 4 3 2 1]
数组的去重：
[1 2 3 4 5]
去重数组的索引数组
[0 1 2 5 6]
[1 2 3 4 5]
返回去重元素的个数
[3 3 2 2 1]
[1 2 3 4 5]
