In [26]:
import random
import numpy as np
import time

In [27]:
a = []
for i in range(1000000):
    a.append(random.random())
start_time = time.time()
sum1 = sum(a)
end_time = time.time()
print("Sum of 1 million random numbers using sum() function: ", sum1)
print("Time taken to calculate sum: ", end_time - start_time, "seconds")

Sum of 1 million random numbers using sum() function:  499900.38121432037
Time taken to calculate sum:  0.0050029754638671875 seconds


In [28]:
b = np.array(a)
start_time = time.time()
sum2 = np.sum(b)
end_time = time.time()
print("Sum of 1 million random numbers using numpy.sum() function: ", sum2)
print("Time taken to calculate sum: ", end_time - start_time, "seconds")

Sum of 1 million random numbers using numpy.sum() function:  499900.3812143072
Time taken to calculate sum:  0.0019905567169189453 seconds


# 4.1创建一维数组

In [29]:
list1 = [1,2,3,4]
#列表强制转换为数组
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


In [30]:
#1、直接通过传入列表创造数组
t1 = np.array([1,2,3,4])
print(t1)
print(type(t1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [31]:
#2、传入range生产序列
t2 = np.array(range(12))
print(t2)
print(type(t2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [32]:
#3、使用numpy自带的np.arange()函数生成序列
t3 = np.arange(0,12,2)
print(t3)
print(type(t3))

[ 0  2  4  6  8 10]
<class 'numpy.ndarray'>


# 4.2创建二维数组

In [33]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 4.3常用属性

In [34]:
#1、获取数组的维数
print(oneArray.ndim)
print(twoArray.ndim)

1
2


In [35]:
#2、获取数组的元素个数
print(oneArray.size)
print(twoArray.size)

4
9


In [36]:
#3、获取数组的形状
print(oneArray.shape)
print(twoArray.shape)

(4,)
(3, 3)


# 4.4调整数组的形状

In [37]:
four = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(four)
print(four.shape)
four.shape = (3,4)
print(four)
print(four.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
