In [2]:
import numpy as np

# 11数组的拼接与分割

In [3]:
#两个原始数组的拼接
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#要求：a,b两个数组的维度相同，要求将其拼接成一个新的数组
c = np.concatenate((a,b),axis=0)
print(c)

d = np.concatenate((a,b),axis=1)
print(d)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [5]:
#根据轴进行堆叠
print(np.stack((a,b),axis=0))
print('-'*50)
print(np.stack((a,b),axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------------------------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [8]:
#3、矩阵的垂直拼接
v1 = [[0,1,2,3,4,5],[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],[18,19,20,21,22,23]]
result = np.vstack((v1,v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [12]:
#4、矩阵的水平拼接
h1 = [[0,1,2],[3,4,5],[6,7,8]]
h2 = [[9,10,11],[12,13,14],[15,16,17]]
result = np.hstack((h1,h2))
print(result)

[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


In [13]:
#数组的分割
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#分割成3个子数组
print(np.split(arr,3,axis=1))

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [17]:
#分割成3个子数组
print(np.split(arr,3,axis=0))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
