In [3]:
import numpy as np

# 二维数组转置
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
arr_T = arr.T
print(arr_T)

# 轴滚动
arr_roll = np.roll(arr, 1, axis=1)
print(arr_roll)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[3 1 2]
 [6 4 5]]
