In [7]:
import pandas as pd
import numpy as np

t = np.arange(24, dtype=float).reshape(4, 6)
t[1, 2] = np.nan
t[3, 5] = np.nan
print(t)

#t.shape[1]是列数
#遍历每一列
for i in range(t.shape[1]):
    #temp_col是每一列的数组
    temp_col = t[:, i]
    #nan_num是nan的个数
    #np.count_nonzero是计算非零元素的个数
    #temp_col!= temp_col是判断是否为nan
    nan_num = np.count_nonzero(temp_col!= temp_col)
    #如果nan的个数不为0
    if nan_num != 0:
        temp_col_not_nan = temp_col[temp_col == temp_col]
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
t

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. nan  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. nan]]
6


array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7., 12.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 11.]])